version: '3.8'

services:
  app:
    image: algchoo/dumpster:laravel-0.0.4
    container_name: laravel_app
    command: >
      bash -c "/scripts/startup.sh
      && php artisan migrate
      && php artisan serve --host=0.0.0.0 --port=80"
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_ENV=$APP_ENV
      - APP_KEY=$APP_KEY

  db:
    image: mariadb:10.5
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
