apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  migrations-seed.sh: |
    #!/bin/bash

    php artisan session:table
    php artisan migrate
    php artisan migrate --path=database/migrations/BlogPostMigration.php

