apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script
data:
  migrations-seed.sh: |
    #!/bin/bash

    php artisan session:table
    php artisan migrate
    php artisan migrate --path=database/migrations/BlogPostMigration.php
    
    /var/www/scripts/load-json.sh
