apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_CONNECTION: "psql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "blog_posts"
  APP_ENV: "testing"
  APP_URL: "http://app.local"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name app.local;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm-service:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        error_page 404 /index.php;
    }
