apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "blog_posts"
  APP_ENV: "testing"
  APP_URL: "http://app.local"
  APP_DEBUG: "false"
  APP_NAME: "dumpster.zip"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name app.local;

        location /build/assets {
            root /var/www/public;
            access_log off;
            expires max;
        }

        location /blog-posts/images/ {
            alias /var/www/public/json/images/;
        }

        # Proxy all other requests to PHP-FPM for Laravel
        location / {
            try_files $uri $uri/ /index.php?$query_string;

            location ~ \.php$ {
                include fastcgi_params;
                fastcgi_pass php-fpm-service:9000;  # Replace with PHP-FPM service hostname
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name; # Matches PHP-FPM's filesystem
            }
        }

        location ~ /\. {
            deny all;
        }
    }

