apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: blog
        image: algchoo/dumpster:blog-0.0.2
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/storage/app
        - name: cache-volume
          mountPath: /var/www/storage/framework/cache/data
        - name: sessions-volume
          mountPath: /var/www/storage/framework/sessions
        - name: views-volume
          mountPath: /var/www/storage/framework/views
        # - name: storage-volume
        #   mountPath: /var/www/storage/logs
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_DATABASE
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_URL
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_KEY
      - name: mysql
        image: mysql:8.4.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        emptyDir: {}
      - name: storage-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: cache-volume
        emptyDir: {}
      - name: sessions-volume
        emptyDir: {}
      - name: views-volume
        emptyDir: {}
