apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/algchoo/blog:2c5a843
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/storage/app
        - name: cache-volume
          mountPath: /var/www/storage/framework/cache/data
        - name: sessions-volume
          mountPath: /var/www/storage/framework/sessions
        - name: views-volume
          mountPath: /var/www/storage/framework/views
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_CONNECTION
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_DATABASE
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_URL
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_DEBUG
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_KEY
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: cache-volume
        emptyDir: {}
      - name: sessions-volume
        emptyDir: {}
      - name: views-volume
        emptyDir: {}
