apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: your-app-tls
  namespace: default
spec:
  secretName: your-app-tls
  dnsNames:
    - app.local
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
