name: Build static assets

on:
  workflow_run:
    workflows: [Pest Tests]
    branches: [main]
    types:
      - completed

jobs:
  build-static-assets:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup-node
      uses: actions/setup-node@v3

    - name: npm-build
      run: npm install && npm run build

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-assets
        path: public/build
        include-hidden-files: true

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: error-message 
        run: echo 'pest tests failed'
