name: Build and release NGINX container images

on:
  workflow_run:
    workflows: [Build static assets]
    branches: [main]
    types: 
      - completed

jobs:
  build-nginx-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: checkout 
      uses: actions/checkout@v3

    - name: get-environment-tag
      id: get-tag
      run: printf '::set-output name=tag::%s' "$(git rev-parse --short HEAD)"

    - name: download-static-assets
      uses: dawidd6/action-download-artifact@v8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build-static-assets.yaml
        path: public/build

    - name: move-static-assets
      run: |
        mv public/build/static-assets/.vite public/build && \
        mv public/build/static-assets/assets public/build

    - name: docker-build-setup
      uses: docker/setup-buildx-action@v1

    - name: docker-qemu-setup
      uses: docker/setup-qemu-action@v1

    - name: github-login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build & push
      run: | 
        docker buildx build -f nginx/Dockerfile --push --platform linux/${{ matrix.platform }} --provenance false -t ghcr.io/algchoo/nginx-${{ matrix.platform }}:${{ steps.get-tag.outputs.tag }} .

  release-scan:
    needs: [build-nginx-container]
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: checkout 
      uses: actions/checkout@v3

    - name: get-environment-tag
      id: get-tag
      run: printf '::set-output name=tag::%s' "$(git rev-parse --short HEAD)"

    - name: github-login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configure-gcp-creds
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: setup-gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJ_ID }}

    - name: retag images
      run: |
        docker pull ghcr.io/algchoo/nginx-${{ matrix.platform }}:${{ steps.get-tag.outputs.tag }}
        docker tag ghcr.io/algchoo/nginx-${{ matrix.platform }}:${{ steps.get-tag.outputs.tag }} us-east1-docker.pkg.dev/blog-images/nginx-${{ matrix.platform }}:${{ steps.get-tag.outputs.tag }}

    - name: validation
      run: |
        echo "Current GCP project: $(gcloud config get-value project)"
        echo "Intended project: ${{ secrets.GCP_PROJ_ID }}"
        docker images

    - name: create ghcr manifest
      run: |
        docker manifest create ghcr.io/algchoo/nginx:${{ steps.get-tag.outputs.tag }} \
        ghcr.io/algchoo/nginx-amd64:${{ steps.get-tag.outputs.tag }} \
        ghcr.io/algchoo/nginx-arm64:${{ steps.get-tag.outputs.tag }}

    - name: create ghcr annotations
      run: |
        docker manifest annotate ghcr.io/algchoo/nginx:${{ steps.get-tag.outputs.tag }} ghcr.io/algchoo/nginx-amd64:${{ steps.get-tag.outputs.tag }} --os linux --arch amd64
        docker manifest annotate ghcr.io/algchoo/nginx:${{ steps.get-tag.outputs.tag }} ghcr.io/algchoo/nginx-arm64:${{ steps.get-tag.outputs.tag }} --os linux --arch arm64

    - name: push ghcr manifest
      run: docker manifest push ghcr.io/algchoo/nginx:${{ steps.get-tag.outputs.tag }}

    - name: set-gcloud-auth
      run: gcloud auth configure-docker us-east1-docker.pkg.dev

    - name: set-gcloud-project
      run: gcloud config set project ${{ secrets.GCP_PROJ_ID }}

    - name: check-gcloud-project
      run: gcloud config list

    - name: create gcr manifest
      run: |
        docker manifest create us-east1-docker.pkg.dev/blog-images/nginx:${{ steps.get-tag.outputs.tag }} \
        us-east1-docker.pkg.dev/blog-images/nginx-amd64:${{ steps.get-tag.outputs.tag }} \
        us-east1-docker.pkg.dev/blog-images/nginx-arm64:${{ steps.get-tag.outputs.tag }}

    - name: create gcr annotations
      run: |
        docker manifest annotate us-east1-docker.pkg.dev/blog-images/nginx:${{ steps.get-tag.outputs.tag }} us-east1-docker.pkg.dev/blog-images/nginx-amd64:${{ steps.get-tag.outputs.tag }} --os linux --arch amd64
        docker manifest annotate us-east1-docker.pkg.dev/blog-images/nginx:${{ steps.get-tag.outputs.tag }} us-east1-docker.pkg.dev/blog-images/nginx-arm64:${{ steps.get-tag.outputs.tag }} --os linux --arch arm64

    - name: push gcr manifest
      run: docker manifest push us-east1-docker.pkg.dev/blog-images/nginx:${{ steps.get-tag.outputs.tag }}

    - name: scan
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'ghcr.io/algchoo/nginx-${{ matrix.platform }}:${{ steps.get-tag.outputs.tag }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: error-message 
        run: echo 'build-static-assets failed'
